#pragma once

// Geometry

#define LOCATION_ATTR_POSITION 0 
#define LOCATION_ATTR_NORMAL 1
#define LOCATION_ATTR_UV 2
#define LOCATION_ATTR_TANGENT 3

#define SET_CAMERA 0 
    #define BINDING_UBO_CAMERA 0

#define SET_LIGHT 1
    #define BINDING_UBO_LIGHT 0

#define SET_SHADOW 2
    #define BINDING_UBO_SHADOW 0

#define SET_MATERIAL 3
    #define BINDING_UBO_MATERIAL 0
    #define BINDING_SAMPLER_ALBEDO 1
    #define BINDING_SAMPLER_EMISSIVE 2
    #define BINDING_SAMPLER_NORMAL 3
    #define BINDING_SAMPLER_ORM 4

#define SET_PBR SET_MATERIAL

// Tonemapping


#define SET_TONEMAP 0
    #define BINDING_UBO_TONEMAP 0