export module spirv_reflect;

#include <spirv-reflect/spirv_reflect.h>;

export 
{
    using ::SpvReflectDescriptorType;
    
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLED_IMAGE;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_INPUT_ATTACHMENT;
    using ::SPV_REFLECT_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR;
    
    using ::SpvReflectShaderModule;
    using ::spvReflectCreateShaderModule;
    using ::spvReflectEnumerateDescriptorBindings;
    using ::SpvReflectDescriptorBinding;
    using ::spvReflectEnumerateDescriptorBindings;
    using ::spvReflectEnumeratePushConstantBlocks;
    using ::SpvReflectBlockVariable;
    using ::spvReflectDestroyShaderModule;
    using ::spvReflectEnumerateInterfaceVariables;
    using ::SpvReflectInterfaceVariable;
    using ::spvReflectEnumerateInputVariables;
    
    using ::SpvReflectResult;
    
    using ::SpvStorageClass;
    using ::SpvReflectDecorationFlags;
    using ::SpvReflectNumericTraits;
    using ::SpvReflectArrayTraits;
    using ::SpvReflectFormat;
    using ::SpvReflectTypeDescription;
    
    
    using ::SPV_REFLECT_RESULT_SUCCESS;
    using ::SPV_REFLECT_RESULT_NOT_READY;
    using ::SPV_REFLECT_RESULT_ERROR_PARSE_FAILED;
    using ::SPV_REFLECT_RESULT_ERROR_ALLOC_FAILED;
    using ::SPV_REFLECT_RESULT_ERROR_RANGE_EXCEEDED;
    using ::SPV_REFLECT_RESULT_ERROR_NULL_POINTER;
    using ::SPV_REFLECT_RESULT_ERROR_INTERNAL_ERROR;
    using ::SPV_REFLECT_RESULT_ERROR_COUNT_MISMATCH;
    using ::SPV_REFLECT_RESULT_ERROR_ELEMENT_NOT_FOUND;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_CODE_SIZE;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_MAGIC_NUMBER;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_UNEXPECTED_EOF;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ID_REFERENCE;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_SET_NUMBER_OVERFLOW;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_STORAGE_CLASS;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_RECURSION;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_INSTRUCTION;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_UNEXPECTED_BLOCK_DATA;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_BLOCK_MEMBER_REFERENCE;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ENTRY_POINT;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_EXECUTION_MODE;
    using ::SPV_REFLECT_RESULT_ERROR_SPIRV_MAX_RECURSIVE_EXCEEDED;
    
    
    using ::SPV_REFLECT_FORMAT_UNDEFINED;
    using ::SPV_REFLECT_FORMAT_R16_UINT;
    using ::SPV_REFLECT_FORMAT_R16_SINT;
    using ::SPV_REFLECT_FORMAT_R16_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R16G16_UINT;
    using ::SPV_REFLECT_FORMAT_R16G16_SINT;
    using ::SPV_REFLECT_FORMAT_R16G16_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R16G16B16_UINT;
    using ::SPV_REFLECT_FORMAT_R16G16B16_SINT;
    using ::SPV_REFLECT_FORMAT_R16G16B16_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R16G16B16A16_UINT;
    using ::SPV_REFLECT_FORMAT_R16G16B16A16_SINT;
    using ::SPV_REFLECT_FORMAT_R16G16B16A16_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R32_UINT;
    using ::SPV_REFLECT_FORMAT_R32_SINT;
    using ::SPV_REFLECT_FORMAT_R32_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R32G32_UINT;
    using ::SPV_REFLECT_FORMAT_R32G32_SINT;
    using ::SPV_REFLECT_FORMAT_R32G32_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R32G32B32_UINT;
    using ::SPV_REFLECT_FORMAT_R32G32B32_SINT;
    using ::SPV_REFLECT_FORMAT_R32G32B32_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R32G32B32A32_UINT;
    using ::SPV_REFLECT_FORMAT_R32G32B32A32_SINT;
    using ::SPV_REFLECT_FORMAT_R32G32B32A32_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R64_UINT;
    using ::SPV_REFLECT_FORMAT_R64_SINT;
    using ::SPV_REFLECT_FORMAT_R64_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R64G64_UINT;
    using ::SPV_REFLECT_FORMAT_R64G64_SINT;
    using ::SPV_REFLECT_FORMAT_R64G64_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R64G64B64_UINT;
    using ::SPV_REFLECT_FORMAT_R64G64B64_SINT;
    using ::SPV_REFLECT_FORMAT_R64G64B64_SFLOAT;
    using ::SPV_REFLECT_FORMAT_R64G64B64A64_UINT;
    using ::SPV_REFLECT_FORMAT_R64G64B64A64_SINT;
    using ::SPV_REFLECT_FORMAT_R64G64B64A64_SFLOAT;
}