#version 450

#include "resources/gbuffer.glsl"
#include "resources/hdr_color_output.glsl"
#include "resources/hdr_color_storage.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform PushRTXGIValidate
{
    vec2 resolution;
    float depth_threshold;
    float normal_threshold;
} pc;

void main()
{
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = (vec2(px) + 0.5) / pc.resolution;
    vec2 motion = get_gbuffer_MOTION_VECTORS(uv).xy;

    vec2 prevUV = uv - motion / pc.resolution;


    if (any(lessThan(prevUV, vec2(0.0))) || any(greaterThan(prevUV, vec2(1.0))))
    {
        imageStore(u_hdr_color_storage[COLOR_OUTPUT_HDR_RTXGI_REPROJECTED], px, vec4(0.0));
        return;
    }

    vec3 history = texture(u_history[COLOR_OUTPUT_HDR_RTXGI], prevUV).rgb;

    float depth = get_gbuffer_DEPTH(uv).r;
    float prevDepth = get_gbuffer_hist_DEPTH(prevUV).r;

    float depthDiff = abs(depth - prevDepth);

    vec3 n = normalize(get_gbuffer_WORLD_NORMAL(uv).xyz * 2.0 - 1.0);
    vec3 pn = normalize(get_gbuffer_hist_WORLD_NORMAL(prevUV).xyz * 2.0 - 1.0);

    float normalDot = dot(n, pn);

    bool valid = (depthDiff < pc.depth_threshold) && (normalDot > pc.normal_threshold);

    imageStore(u_hdr_color_storage[COLOR_OUTPUT_HDR_RTXGI_REPROJECTED], px, vec4(history, valid ? 1.0 : 0.0));
}