"""
Generates patched copies of a few MSVC STL headers so that containers and
algorithms work with C++26 consteval-only types (std::meta::info).

usage: python tools/gen_stl_overlay.py <msvc-include-dir> <output-dir>

P2996 makes every function that touches a consteval-only type an immediate
function; that only works if the function is constexpr (it then escalates to
consteval). A handful of MSVC STL helpers on runtime-only paths (memmove
fast paths, debug-iterator bookkeeping) are not constexpr, so e.g.
std::vector<std::meta::info> fails to compile. libc++ in bloomberg/clang-p2996
carries equivalent fixes. Making these helpers constexpr is harmless for
ordinary types since C++23 (P2448) allows non-constant code in constexpr
functions.

It also adds a <cwctype> wrapper that exports <meta> from the `std` module:
MSVC's modules/std.ixx has no <meta> yet, and <cwctype> is the last header it
includes (no other STL header includes <cwctype>), so at that point every
header <meta> depends on is already in the module purview. The project builds
MSVC's std.ixx as is instead of a modified copy, so IDEs that build `std` from
the MSVC toolset themselves (Rider / ReSharper C++) see a single `std` module.

The output directory is put in front of the STL include path; untouched
headers keep resolving to the original STL.
"""
import os
import re
import sys

# header -> functions whose definitions get `constexpr`
PATCHES = {
    "xutility": ["_Copy_memmove_tail", "_Copy_memmove", "_Copy_memmove_n", "_Copy_backward_memmove"],
    "vector": ["_Orphan_range_locked"],
}

src_dir, out_dir = sys.argv[1], sys.argv[2]
os.makedirs(out_dir, exist_ok=True)

ok = True
for header, funcs in PATCHES.items():
    with open(os.path.join(src_dir, header), encoding="utf-8") as f:
        text = f.read()
    for fn in funcs:
        # a definition line: optional specifiers, return type, name, '(' - but not a call
        rx = re.compile(
            r"^(?P<indent>[ \t]*)(?P<pre>(?:_NODISCARD[ \t]+)?(?:static[ \t]+)?)"
            r"(?P<ret>(?!return\b)[\w:<>]+[ \t]+)" + re.escape(fn) + r"\(",
            re.M)
        text, n = rx.subn(lambda m: f"{m.group('indent')}{m.group('pre')}constexpr {m.group('ret')}{fn}(", text)
        if n == 0:
            print(f"gen_stl_overlay: warning: definition of {fn} not found in <{header}>", file=sys.stderr)
            ok = False
    banner = "// Patched copy of the MSVC STL <%s> generated by tools/gen_stl_overlay.py - do not edit.\n" % header
    out_path = os.path.join(out_dir, header)
    new = banner + text
    old = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else None
    if old != new:
        with open(out_path, "w", encoding="utf-8", newline="") as f:
            f.write(new)

CWCTYPE_WRAPPER = """// Generated by tools/gen_stl_overlay.py - do not edit.
// <cwctype> that also exports C++26 <meta> when building MSVC's std.ixx (see the script docs).
#include_next <cwctype>

#if defined(_BUILD_STD_MODULE) && !defined(_RHEA_STD_MODULE_META)
#define _RHEA_STD_MODULE_META
export {
#include <meta>
}
#endif
"""

SOURCE_LOCATION_WRAPPER = """// Generated by tools/gen_stl_overlay.py - do not edit.
// Rider's code model doesn't know __builtin_FUNCSIG (the default for std::source_location::current()
// with the MSVC STL), which hides std::source_location from it. Compilers are not affected.
#if defined(__RESHARPER__) && !defined(_USE_DETAILED_FUNCTION_NAME_IN_SOURCE_LOCATION)
#define _USE_DETAILED_FUNCTION_NAME_IN_SOURCE_LOCATION 0
#endif
#include_next <source_location>
"""

extra_files = {"cwctype": CWCTYPE_WRAPPER, "source_location": SOURCE_LOCATION_WRAPPER}
for name, new in extra_files.items():
    out_path = os.path.join(out_dir, name)
    old = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else None
    if old != new:
        with open(out_path, "w", encoding="utf-8", newline="") as f:
            f.write(new)

sys.exit(0 if ok else 1)
