"""
Generates a <meta> header usable with the MSVC STL from the libc++ <meta>
shipped with the bloomberg/clang-p2996 fork.

usage: python tools/gen_meta_msstl.py D:/toolchains/clang-p2996

The fork's header only depends on a handful of libc++ internals (namespace
macros and <__ranges/*> detail headers), which are replaced with standard
equivalents here. std::meta::source_location_of needs libc++'s
std::source_location::__impl, which the MSVC STL does not have, so it is
turned into a template that fails to compile only when actually used.

Rider's code model (ReSharper C++) understands reflection but doesn't report
__has_feature(reflection) etc., which would hide the whole header from it, so
the feature checks are routed through _RHEA_META_FEATURE, true for Rider.
"""
import os
import re
import sys

fork = sys.argv[1] if len(sys.argv) > 1 else "D:/toolchains/clang-p2996"
src = os.path.join(fork, "libcxx", "include", "meta")
dst_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "thirdparty", "reflection", "include")
dst = os.path.normpath(os.path.join(dst_dir, "meta"))

text = open(src, encoding="utf-8").read().replace("\r\n", "\n")

prologue = """
// ---- MSVC STL adaptation (generated by tools/gen_meta_msstl.py) ----
#include <ranges>
#include <array>
#include <concepts>
#include <iterator>
#include <memory>
#include <utility>

#define _LIBCPP_BEGIN_NAMESPACE_STD namespace std {
#define _LIBCPP_END_NAMESPACE_STD }
#define _LIBCPP_BEGIN_NAMESPACE_META namespace std { namespace meta {
#define _LIBCPP_END_NAMESPACE_META } }
#define _LIBCPP_BEGIN_NAMESPACE_REFLECTION_V2 _LIBCPP_BEGIN_NAMESPACE_META inline namespace reflection_v2 {
#define _LIBCPP_END_NAMESPACE_REFLECTION_V2 } _LIBCPP_END_NAMESPACE_META
#ifdef __RESHARPER__
#define _RHEA_META_FEATURE(feature) 1
#else
#define _RHEA_META_FEATURE(feature) __has_feature(feature)
#endif
// --------------------------------------------------------------------
"""

text = text.replace("#include <__config>\n", prologue, 1)
text = re.sub(r"#include <__ranges/[a-z_]+\.h>\n", "", text)

# [meta.unary.prop] is_consteval_only lives in libc++'s <type_traits>; the MSVC STL lacks it
consteval_only = """
#if __has_feature(reflection)
_LIBCPP_BEGIN_NAMESPACE_STD
template <class _Tp>
struct is_consteval_only : integral_constant<bool, __is_consteval_only(_Tp)> {};
template <class _Tp>
inline constexpr bool is_consteval_only_v = __is_consteval_only(_Tp);

#if !defined(__cpp_lib_string_view) || __cpp_lib_string_view < 202403L
// P2591 (C++26) string + string_view, used by the pretty printer below
template <class _Ch, class _Tr, class _Al>
constexpr basic_string<_Ch, _Tr, _Al> operator+(const basic_string<_Ch, _Tr, _Al>& __l,
                                                type_identity_t<basic_string_view<_Ch, _Tr>> __r) {
  basic_string<_Ch, _Tr, _Al> __s = __l;
  __s.append(__r);
  return __s;
}
template <class _Ch, class _Tr, class _Al>
constexpr basic_string<_Ch, _Tr, _Al> operator+(basic_string<_Ch, _Tr, _Al>&& __l,
                                                type_identity_t<basic_string_view<_Ch, _Tr>> __r) {
  __l.append(__r);
  return std::move(__l);
}
template <class _Ch, class _Tr, class _Al>
constexpr basic_string<_Ch, _Tr, _Al> operator+(type_identity_t<basic_string_view<_Ch, _Tr>> __l,
                                                const basic_string<_Ch, _Tr, _Al>& __r) {
  basic_string<_Ch, _Tr, _Al> __s(__l);
  __s.append(__r);
  return __s;
}
template <class _Ch, class _Tr, class _Al>
constexpr basic_string<_Ch, _Tr, _Al> operator+(type_identity_t<basic_string_view<_Ch, _Tr>> __l,
                                                basic_string<_Ch, _Tr, _Al>&& __r) {
  __r.insert(0, __l);
  return std::move(__r);
}
#endif
_LIBCPP_END_NAMESPACE_STD
#endif
"""
anchor = "#if __has_feature(reflection)\n"
idx = text.index(anchor)
text = text[:idx] + consteval_only + "\n" + text[idx:]

# The MSVC STL declares std::ptrdiff_t / std::nullptr_t as using-declarations
# (`using ::ptrdiff_t;`), which can't be reflected. Name the types directly.
text = text.replace("^^ptrdiff_t", "^^decltype(static_cast<char*>(nullptr) - static_cast<char*>(nullptr))")
text = text.replace("^^nullptr_t", "^^decltype(nullptr)")

# P2497 (to_chars_result::operator bool) is missing from the MSVC STL
n = text.count("if (!to_chars(")
text = re.sub(r"if \(!to_chars\(([^;]*?)\)\)\n", r"if (to_chars(\1).ec != errc{})\n", text)
assert n and text.count("if (!to_chars(") == 0, "to_chars pattern changed"

# The MSVC STL's make_signed<float> is a hard static_assert, not reached with libc++
old = "auto U = make_signed(R);"
assert old in text
text = text.replace(old, "auto U = is_integral_type(R) && remove_cv(R) != ^^bool ? make_signed(R) : R;")

old_sl = re.search(
    r"consteval auto source_location_of\(info r\) -> source_location \{\n.*?\n\}\n",
    text, re.S)
assert old_sl, "source_location_of definition not found"
text = text.replace(old_sl.group(0),
    "template <class _Tp = void>\n"
    "consteval auto source_location_of(info r) -> source_location {\n"
    "  static_assert(sizeof(_Tp*) == 0,\n"
    "      \"std::meta::source_location_of is not supported with the MSVC STL \"\n"
    "      \"(it lacks std::source_location::__impl)\");\n"
    "  return {};\n"
    "}\n")

# after the anchor lookup above, which matches the original spelling
text = text.replace("#if __has_feature(", "#if _RHEA_META_FEATURE(")
assert not re.search(r"^\s*#\s*(if|elif).*__has_feature\(", text, re.M), "unexpected __has_feature checks in <meta>"

undefs = """
#undef _RHEA_META_FEATURE
#undef _LIBCPP_BEGIN_NAMESPACE_STD
#undef _LIBCPP_END_NAMESPACE_STD
#undef _LIBCPP_BEGIN_NAMESPACE_META
#undef _LIBCPP_END_NAMESPACE_META
#undef _LIBCPP_BEGIN_NAMESPACE_REFLECTION_V2
#undef _LIBCPP_END_NAMESPACE_REFLECTION_V2
"""
idx = text.rfind("#endif")
text = text[:idx] + undefs + "\n" + text[idx:]

os.makedirs(os.path.join(dst_dir, "experimental"), exist_ok=True)
open(dst, "w", encoding="utf-8", newline="\n").write(text)
open(os.path.join(dst_dir, "experimental", "meta"), "w", encoding="utf-8", newline="\n").write(
    "#pragma once\n#include <meta>\n")
print("written", dst)
