#ifndef RESOURCES_GBUFFER
#define RESOURCES_GBUFFER

#ifndef NUM_GBUFFER_SLOTS
    #define NUM_GBUFFER_SLOTS 0
    #error "NUM_GBUFFER_SLOTS not provided"
#endif

const uint GBUFFER_SLOT_NORMAL = 0;
const uint GBUFFER_SLOT_WORLD_NORMAL = 1;
const uint GBUFFER_SLOT_DEPTH = 2;
const uint GBUFFER_SLOT_LINEAR_DEPTH = 3;
const uint GBUFFER_SLOT_ALBEDO_ROUGHNESS = 4;
const uint GBUFFER_SLOT_POSITION = 5;
const uint GBUFFER_SLOT_MOTION_VECTORS = 6;
const uint GBUFFER_SLOT_GEOMETRY_NORMAL = 7;
const uint GBUFFER_SLOT_EMISSIVE = 8;

const uint GBUFFER_NUM_SLOTS = NUM_GBUFFER_SLOTS;

#ifndef SET_GBUFFER
    #define SET_GBUFFER 0
    #error "SET_GBUFFER definition is missing"
#endif
#ifndef BINDING_SAMPLER_ARRAY_GBUFFER
    #define BINDING_SAMPLER_ARRAY_GBUFFER 0
    #error "BINDING_SAMPLER_ARRAY_GBUFFER definition is missing. Provide this resource: gbuffer"
#endif
#ifndef BINDING_SAMPLER_ARRAY_GBUFFER_HIST
    #define BINDING_SAMPLER_ARRAY_GBUFFER_HIST 0
    #error "BINDING_SAMPLER_ARRAY_GBUFFER_HIST definition is missing. Provide this resource: gbuffer"
#endif

layout(set = SET_GBUFFER, binding = BINDING_SAMPLER_ARRAY_GBUFFER) 
uniform sampler2D u_gbuffer[GBUFFER_NUM_SLOTS];

layout(set = SET_GBUFFER, binding = BINDING_SAMPLER_ARRAY_GBUFFER_HIST)
uniform sampler2D u_gbuffer_hist[GBUFFER_NUM_SLOTS];

#define DECLARE_GBUFFER_GETTER(func, index) \
    vec4 func(vec2 uv) \
    { \
        return texture(u_gbuffer[index], uv); \
    }

#define DECLARE_GBUFFER_HIST_GETTER(func, index) \
    vec4 func(vec2 uv) \
    { \
        return texture(u_gbuffer_hist[index], uv); \
    }

// 0
DECLARE_GBUFFER_GETTER(get_gbuffer_NORMAL, GBUFFER_SLOT_NORMAL)
// 1
DECLARE_GBUFFER_GETTER(get_gbuffer_WORLD_NORMAL, GBUFFER_SLOT_WORLD_NORMAL)
// 2
DECLARE_GBUFFER_GETTER(get_gbuffer_DEPTH, GBUFFER_SLOT_DEPTH)
// 3
DECLARE_GBUFFER_GETTER(get_gbuffer_LINEAR_DEPTH, GBUFFER_SLOT_LINEAR_DEPTH)
// 4
DECLARE_GBUFFER_GETTER(get_gbuffer_ALBEDO_ROUGHNESS, GBUFFER_SLOT_ALBEDO_ROUGHNESS)
// 5
DECLARE_GBUFFER_GETTER(get_gbuffer_POSITION, GBUFFER_SLOT_POSITION)
// 6
DECLARE_GBUFFER_GETTER(get_gbuffer_MOTION_VECTORS, GBUFFER_SLOT_MOTION_VECTORS)
// 7
DECLARE_GBUFFER_GETTER(get_gbuffer_GEOMETRY_NORMAL, GBUFFER_SLOT_GEOMETRY_NORMAL)
// 8
DECLARE_GBUFFER_GETTER(get_gbuffer_EMISSIVE, GBUFFER_SLOT_EMISSIVE)



// 0
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_NORMAL, GBUFFER_SLOT_NORMAL)
// 1
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_WORLD_NORMAL, GBUFFER_SLOT_WORLD_NORMAL)
// 3
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_DEPTH, GBUFFER_SLOT_DEPTH)
// 4
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_LINEAR_DEPTH, GBUFFER_SLOT_LINEAR_DEPTH)
// 5
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_ALBEDO_ROUGHNESS, GBUFFER_SLOT_ALBEDO_ROUGHNESS)
// 6
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_POSITION, GBUFFER_SLOT_POSITION)
// 7
DECLARE_GBUFFER_HIST_GETTER(get_gbuffer_hist_MOTION_VECTORS, GBUFFER_SLOT_MOTION_VECTORS)
// 8
DECLARE_GBUFFER_GETTER(get_gbuffer_hist_EMISSIVE, GBUFFER_SLOT_EMISSIVE)

#endif  // RESOURCES_GBUFFER