// Source - https://stackoverflow.com/a/70653045
// Posted by Seungwoo Kang, modified by community. See post 'Timeline' for change history
// Retrieved 2025-12-18, License - CC BY-SA 4.0

#pragma once

#define PRIVATE_RHEA_CONCATENATE(x,y) x##y


#define PRIVATE_RHEA_EXPAND(x) x
#define PRIVATE_RHEA_FOR_EACH_COLON_1(what, x, ...) what(x)
#define PRIVATE_RHEA_FOR_EACH_COLON_2(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_1(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_3(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_2(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_4(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_3(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_5(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_4(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_6(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_5(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_7(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_6(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_8(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_7(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_9(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_8(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_10(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_9(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_11(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_10(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_12(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_11(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_13(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_12(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_14(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_13(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_15(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_14(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_16(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_15(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_17(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_16(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_18(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_17(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_19(what, x, ...) what(x),PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_18(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_NARG(...) PRIVATE_RHEA_FOR_EACH_COLON_NARG_(__VA_ARGS__, PRIVATE_RHEA_FOR_EACH_COLON_RSEQ_N())
#define PRIVATE_RHEA_FOR_EACH_COLON_NARG_(...) PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_COLON_ARG_N(__VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_COLON_ARG_N(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19, N, ...) N
#define PRIVATE_RHEA_FOR_EACH_COLON_RSEQ_N() 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 

#define PRIVATE_RHEA_FOR_EACH_COLON_(N, what, ...) PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_CONCATENATE(PRIVATE_RHEA_FOR_EACH_COLON_, N)(what, __VA_ARGS__))
#define RHEA_FOR_EACH_COLON(what, ...) PRIVATE_RHEA_FOR_EACH_COLON_(PRIVATE_RHEA_FOR_EACH_COLON_NARG(__VA_ARGS__), what, __VA_ARGS__)






// Source - https://stackoverflow.com/a/70653045
// Posted by Seungwoo Kang, modified by community. See post 'Timeline' for change history
// Retrieved 2025-12-18, License - CC BY-SA 4.0

#pragma once
#define PRIVATE_RHEA_EXPAND(x) x
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_1(what, x, ...) what(x)
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_2(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_1(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_3(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_2(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_4(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_3(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_5(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_4(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_6(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_5(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_7(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_6(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_8(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_7(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_9(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_8(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_10(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_9(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_11(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_10(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_12(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_11(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_13(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_12(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_14(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_13(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_15(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_14(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_16(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_15(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_17(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_16(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_18(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_17(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_19(what, x, ...) what(x);PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_18(what, __VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_NARG(...) PRIVATE_RHEA_FOR_EACH_SEMICOLON_NARG_(__VA_ARGS__, PRIVATE_RHEA_FOR_EACH_SEMICOLON_RSEQ_N())
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_NARG_(...) PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_FOR_EACH_SEMICOLON_ARG_N(__VA_ARGS__))
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_ARG_N(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19, N, ...) N
#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_RSEQ_N() 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 

#define PRIVATE_RHEA_FOR_EACH_SEMICOLON_(N, what, ...) PRIVATE_RHEA_EXPAND(PRIVATE_RHEA_CONCATENATE(PRIVATE_RHEA_FOR_EACH_SEMICOLON_, N)(what, __VA_ARGS__))
#define RHEA_FOR_EACH_SEMICOLON(what, ...) PRIVATE_RHEA_FOR_EACH_SEMICOLON_(PRIVATE_RHEA_FOR_EACH_SEMICOLON_NARG(__VA_ARGS__), what, __VA_ARGS__)




